import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import prettier from 'eslint-config-prettier'

/*
 * FinSoft lint configuration.
 *
 * Most of what is here is not style. It is the mechanical half of the ADRs:
 * each block below cites the document it enforces. Formatting is Prettier's
 * job and is switched off here via eslint-config-prettier.
 *
 * Import boundaries between packages are dependency-cruiser's job
 * (.dependency-cruiser.cjs). This file handles rules that need to look at
 * syntax rather than at the module graph.
 */

/** Decimal libraries. ADR-0011 / ADR-0014: exactly one, only in packages/validation. */
const DECIMAL_LIBS = ['decimal.js', 'decimal.js-light', 'big.js', 'bignumber.js']

/** Network clients. ADR-0001: the kernels have no network. */
const HTTP_CLIENTS = ['axios', 'node-fetch', 'undici', 'got', 'superagent', 'ky']

/** ADR-0012: fiscal period locking has no system bypass, so these names may not exist. */
const PERIOD_BYPASS = ['bypassPeriod', 'skipPeriodCheck', 'forcePost', 'systemActor']

const invariantSyntax = [
  {
    // ADR-0013. A numeric or int8 parser override silently destroys ADR-0011.
    selector: "CallExpression[callee.property.name='setTypeParser']",
    message:
      'ADR-0013: type parser overrides are forbidden. numeric and int8 must reach TypeScript as strings.',
  },
  {
    // ADR-0013. pg.defaults.parseInt8 = true rewires OID 20 without touching setTypeParser.
    selector: "MemberExpression[object.name='pg'][property.name='defaults']",
    message: 'ADR-0013: pg.defaults is forbidden — it can rewire type parsing behind the ADR.',
  },
  {
    // ADR-0013. sql.raw does not parameterise, unlike the sql tag it hides behind.
    selector: "CallExpression[callee.object.name='sql'][callee.property.name='raw']",
    message: 'ADR-0013: sql.raw does not parameterise. Use the sql tag, or an allowlisted helper.',
  },
  {
    // ADR-0013. DDL lives in database/migrations/*.sql, never in TypeScript.
    selector: "MemberExpression[object.name=/^(db|tx|trx|kysely)$/][property.name='schema']",
    message: 'ADR-0013: DDL belongs in database/migrations/*.sql, not in a Kysely schema builder.',
  },
  {
    selector: "NewExpression[callee.name='Migrator']",
    message: "ADR-0013: Kysely's Migrator is not used. Migrations are numbered .sql files.",
  },
  {
    /*
     * ADR-0014. The configured constructor is frozen; reconfiguring it is
     * retroactive and invisible.
     *
     * This name list is the second line of defence, not the first. The first
     * is the import ban below plus the dependency-cruiser rule: a decimal
     * constructor binding cannot exist outside packages/validation at all.
     * Keep FinDecimal here — it is the name the real binding uses, and an
     * earlier version of this list omitted it.
     */
    selector:
      "CallExpression[callee.property.name='set'][callee.object.name=/^(FinDecimal|Decimal|Big|BigNumber|D|M)$/]",
    message:
      'ADR-0014: decimal configuration exists at exactly one frozen clone site in packages/validation.',
  },
  {
    // ADR-0012. Named in the ADR's own compliance section as a code-search check.
    selector: `Identifier[name=/^(${PERIOD_BYPASS.join('|')})$/]`,
    message:
      'ADR-0012: a closed period rejects postings from jobs, imports and scripts alike. There is no bypass.',
  },
  {
    // AGENTS.md rule 4 / anti-pattern 6. A red test is information, not an obstacle.
    selector: "MemberExpression[object.name=/^(it|test|describe)$/][property.name='skip']",
    message: 'AGENTS.md rule 4: never disable a test to reach green. Report the failure instead.',
  },
  {
    // .only silently reduces a suite to one case while still reporting success.
    selector: "MemberExpression[object.name=/^(it|test|describe)$/][property.name='only']",
    message: '.only silently skips the rest of the suite. Remove it before committing.',
  },
]

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/coverage/**',
      'ui-prototype/**',
      'packages/database/src/generated/**',
      'tools/parity/**',
      // Generated by Next and gitignored; not ours to lint.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  /* ---------------------------------------------------------------- *
   * Repository-wide invariants
   * ---------------------------------------------------------------- */
  {
    rules: {
      'no-restricted-syntax': ['error', ...invariantSyntax],
      'no-restricted-imports': [
        'error',
        {
          paths: DECIMAL_LIBS.map((name) => ({
            name,
            message:
              'ADR-0011/ADR-0014: import Money from @finsoft/validation. The decimal library lives there and nowhere else.',
          })),
        },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  /* ---------------------------------------------------------------- *
   * packages/validation — the one place a decimal library may live
   * ADR-0011, ADR-0014
   * ---------------------------------------------------------------- */
  {
    files: ['packages/validation/**/*.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },

  /* ---------------------------------------------------------------- *
   * The kernels — no network, no HTTP, no NestJS, no feature modules
   * ADR-0001, ADR-0005, ARCHITECTURE.md §5
   * ---------------------------------------------------------------- */
  {
    files: ['packages/accounting-kernel/**/*.ts', 'packages/inventory-kernel/**/*.ts'],
    rules: {
      'no-restricted-globals': [
        'error',
        { name: 'fetch', message: 'ADR-0001: the kernels have no network.' },
      ],
      'no-restricted-imports': [
        'error',
        {
          paths: [
            ...DECIMAL_LIBS.map((name) => ({
              name,
              message: 'ADR-0011: import Money from @finsoft/validation.',
            })),
            ...HTTP_CLIENTS.map((name) => ({
              name,
              message: 'ADR-0001: the kernels have no network.',
            })),
            {
              name: '@nestjs/common',
              message: 'ARCHITECTURE §3: the kernels know nothing about HTTP or NestJS.',
            },
          ],
          patterns: [
            {
              group: [
                '**/modules/**',
                '@finsoft/reporting',
                '@finsoft/auth',
                '@finsoft/permissions',
              ],
              message:
                'ARCHITECTURE §5: a kernel imports database, validation and shared-types — and nothing else.',
            },
          ],
        },
      ],
    },
  },

  /* ---------------------------------------------------------------- *
   * Module domain layers — pure TypeScript
   * ARCHITECTURE.md §2: "no NestJS, no ORM, no HTTP"
   * ---------------------------------------------------------------- */
  {
    files: ['modules/*/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: 'kysely', message: 'ARCHITECTURE §2: domain/ is pure TypeScript — no ORM.' },
            { name: 'pg', message: 'ARCHITECTURE §2: domain/ is pure TypeScript — no driver.' },
            {
              name: '@finsoft/database',
              message: 'ARCHITECTURE §2: domain/ never sees a connection or a row type.',
            },
            ...DECIMAL_LIBS.map((name) => ({
              name,
              message: 'ADR-0011: import Money from @finsoft/validation.',
            })),
          ],
          patterns: [
            {
              group: ['@nestjs/*', 'express', 'fastify'],
              message: 'ARCHITECTURE §2: domain/ has no HTTP and no framework.',
            },
          ],
        },
      ],
    },
  },

  /* ---------------------------------------------------------------- *
   * apps/web — UI only, no business rules
   * NON_NEGOTIABLES rule 19, ARCHITECTURE.md §5
   * ---------------------------------------------------------------- */
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            ...DECIMAL_LIBS.map((name) => ({
              name,
              message: 'Rule 19: the browser never computes a monetary figure.',
            })),
            {
              name: '@finsoft/accounting-kernel',
              message: 'Rule 19: business logic lives in the backend domain layer, never in React.',
            },
            {
              name: '@finsoft/inventory-kernel',
              message: 'Rule 19: business logic lives in the backend domain layer, never in React.',
            },
            {
              name: '@finsoft/database',
              message: 'ARCHITECTURE §5: apps/web reaches ui, shared-types and validation only.',
            },
            { name: 'kysely', message: 'ARCHITECTURE §5: the browser has no database.' },
            { name: 'pg', message: 'ARCHITECTURE §5: the browser has no database.' },
          ],
          patterns: [
            {
              group: ['**/modules/*/domain/**', '**/modules/*/application/**'],
              message: 'ARCHITECTURE §5: apps/web never reaches into a module.',
            },
          ],
        },
      ],
    },
  },

  /* ---------------------------------------------------------------- *
   * React. apps/web is the only React surface; the hooks rules are here
   * because a lint setup that cannot resolve this app's own
   * eslint-disable directives is not a working lint setup.
   * ---------------------------------------------------------------- */
  {
    files: ['apps/web/**/*.{ts,tsx}', 'packages/ui/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  /* ---------------------------------------------------------------- *
   * Config files and scripts
   * ---------------------------------------------------------------- */
  {
    files: ['*.config.{js,mjs,ts}', 'tools/**/*.mjs'],
    rules: { 'no-console': 'off' },
  },
  {
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { module: 'writable', require: 'readonly', __dirname: 'readonly' },
    },
    rules: { 'no-console': 'off' },
  },

  prettier,
)
