import { expect, test } from '@playwright/test'

/*
 * The login journey (docs/design-system/pages/login/README.md), against a
 * mocked API rather than a real one — m1-auth's /api/auth/* endpoints do not
 * exist yet, and this spec's job is the SCREEN's behaviour, not the auth
 * lane's. Runs on the `web` Playwright project (playwright.config.ts), which
 * starts apps/web on its own origin; every request the fixed contract names
 * is intercepted with `page.route` before it would otherwise fail to connect.
 *
 * Covers the three journeys the M1-W brief names explicitly: invalid
 * credentials, rate limiting, and success -> redirect. The unit/component
 * suite (apps/web/src/test/login.test.tsx) covers every other state in
 * detail; this file proves the same behaviour survives a real browser, a
 * real Next.js render and real navigation.
 */

const USER = { id: 'u1', fullName: 'Ada Lovelace', email: 'ada@acme.test' }
const TENANT = { id: 't1', code: 'ACME', name: 'Acme Trading' }

test.beforeEach(async ({ page }) => {
  // The on-load silent refresh/session check (apps/web/src/lib/api/auth-context.tsx)
  // fires on every route, /login included. Mocked to a fast 401 by default so
  // it never depends on a real, unreachable API — individual tests below
  // override this once a login actually succeeds.
  await page.route('**/api/auth/me', (route) => route.fulfill({ status: 401, json: {} }))
  await page.route('**/api/auth/refresh', (route) => route.fulfill({ status: 401, json: {} }))
})

test('invalid credentials shows one generic banner, never which field', async ({ page }) => {
  await page.route('**/api/auth/login', (route) =>
    route.fulfill({
      status: 401,
      json: { error: 'invalid_credentials', message: 'Incorrect tenant code, email or password.' },
    }),
  )

  await page.goto('/login')
  await page.getByLabel(/tenant code/i).fill('ACME')
  await page.getByLabel(/^email/i).fill('ada@acme.test')
  await page.getByLabel(/^password/i).fill('wrong-password')
  await page.getByRole('button', { name: 'Sign in' }).click()

  const banner = page.getByRole('status')
  await expect(banner).toHaveText('Incorrect tenant code, email or password.')
  // Still on /login — a failed attempt does not navigate anywhere.
  await expect(page).toHaveURL(/\/login/)
  await expect(page.getByRole('button', { name: 'Sign in' })).toBeEnabled()
})

test('rate limiting shows the Retry-After countdown and disables submit until it elapses', async ({
  page,
}) => {
  await page.route('**/api/auth/login', (route) =>
    route.fulfill({ status: 429, headers: { 'Retry-After': '2' }, json: {} }),
  )

  await page.goto('/login')
  await page.getByLabel(/tenant code/i).fill('ACME')
  await page.getByLabel(/^email/i).fill('ada@acme.test')
  await page.getByLabel(/^password/i).fill('x')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await expect(page.getByRole('status')).toContainText(/too many attempts/i)
  const submit = page.getByRole('button', { name: /try again in \d+s/i })
  await expect(submit).toBeDisabled()

  // The countdown reaches zero and the form becomes usable again, with no
  // reload and no re-navigation.
  await expect(page.getByRole('button', { name: /^sign in$/i })).toBeEnabled({ timeout: 5_000 })
})

test('success signs in and redirects to the dashboard', async ({ page }) => {
  let loggedIn = false

  await page.route('**/api/auth/me', (route) => {
    if (loggedIn) {
      return route.fulfill({
        status: 200,
        json: { user: USER, tenant: TENANT, sessionId: 's1', permissionVersion: 1 },
      })
    }
    return route.fulfill({ status: 401, json: {} })
  })
  await page.route('**/api/auth/login', (route) => {
    loggedIn = true
    return route.fulfill({
      status: 200,
      json: { accessToken: 'e2e-token', expiresIn: 900, user: USER, tenant: TENANT },
    })
  })

  await page.goto('/login')
  await page.getByLabel(/tenant code/i).fill('ACME')
  await page.getByLabel(/^email/i).fill('ada@acme.test')
  await page.getByLabel(/^password/i).fill('correct-password')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await expect(page).toHaveURL(/\/dashboard/, { timeout: 15_000 })
  // The real shell renders post-login, with the real identity in its header —
  // not the login form any more.
  await expect(page.getByRole('button', { name: /sign out/i })).toBeVisible()
})

test('a malicious ?next= is ignored — signing in still lands on /dashboard, never off-site', async ({
  page,
}) => {
  // Security review (this task): apps/web/src/lib/api/auth-context.tsx's
  // "already authenticated on /login" effect used to hand `next` straight to
  // the router. A link like this one — sent by an attacker, not generated by
  // this app — must not be able to redirect a signed-in user off-site.
  let loggedIn = false

  await page.route('**/api/auth/me', (route) => {
    if (loggedIn) {
      return route.fulfill({
        status: 200,
        json: { user: USER, tenant: TENANT, sessionId: 's1', permissionVersion: 1 },
      })
    }
    return route.fulfill({ status: 401, json: {} })
  })
  await page.route('**/api/auth/login', (route) => {
    loggedIn = true
    return route.fulfill({
      status: 200,
      json: { accessToken: 'e2e-token', expiresIn: 900, user: USER, tenant: TENANT },
    })
  })

  await page.goto('/login?next=https%3A%2F%2Fevil.example%2Flogin')
  await page.getByLabel(/tenant code/i).fill('ACME')
  await page.getByLabel(/^email/i).fill('ada@acme.test')
  await page.getByLabel(/^password/i).fill('correct-password')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await expect(page).toHaveURL(/\/dashboard/, { timeout: 15_000 })
  await expect(page.getByRole('button', { name: /sign out/i })).toBeVisible()
})

test('an unauthenticated visit to a protected route redirects to /login?next=<path>', async ({
  page,
}) => {
  // beforeEach already mocks /api/auth/me and /api/auth/refresh to 401 — this
  // is exactly "no session", the case the client-side guard exists for
  // (apps/web/src/lib/api/auth-context.tsx, brief acceptance criterion 5/6).
  await page.goto('/dashboard')

  await expect(page).toHaveURL(/\/login\?next=%2Fdashboard/, { timeout: 15_000 })
  await expect(page.getByRole('button', { name: 'Sign in' })).toBeVisible()
})
