'use client'
/* Dashboard and the seven compact module screens that lived inside
 * ui-prototype/src/App.tsx. Bodies are verbatim; only imports were rewritten. */
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { useLocation, useNavigate } from '@/lib/router'
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, BadgeCheck, Bell, BookOpen, BookUser, Boxes, CalendarCheck, CalendarDays, ChartNoAxesCombined,
  Check, ChevronDown, ChevronRight, CircleHelp, Mail, Settings, ChevronsLeft, CircleDollarSign, ClipboardCheck, ClipboardList, ClipboardPlus, Clock3, ContactRound, Download,
  Eye, FileChartColumn, FilePlus2, FileText, Filter, HandCoins, History, Landmark, LayoutDashboard, LockKeyhole, Menu, PackageCheck, Pill, Plus, Printer,
  ReceiptText, ScrollText, Search, Settings2, ShieldCheck, ShoppingBag, ShoppingCart, Sparkles, TableProperties, Truck,
  TrendingUp, Users, WalletCards, Navigation, ArrowLeftRight, Banknote, Barcode, BellRing, Building2, ChartPie, Database, FolderTree, Grid2x2, Layers, ListChecks, MapPin, PackageSearch, Percent, Scale, ShieldAlert, Store, Tag, Target, UserCog, UsersRound, Wallet, Warehouse, Coins, Ellipsis, type LucideIcon,
} from 'lucide-react'
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { actionPermissions, chartData, nav, roles, users, type Master, type NavChild, type NavItem, type Product, type Purchase, type Sale } from '@/mocks/api'
import { usePersistentData } from '@/mocks/api'
import { AccountDetail, EmployeeDetail, MasterDetail, ProductDetail, PurchaseDetail, SaleDetail, UserDetail } from './detail-pages'
import { AccountsPayable, AccountsReceivable } from './finance-pages'
import { ChartOfAccounts } from './chart-of-accounts'
import { AccountLedger } from './account-ledger'
import { BankTransactions } from './bank-transactions'
import { FieldSales, PeriodClose } from './trade-pages'
import { CustomerDetail, PartyList, VendorDetail } from './parties'
import { CreditLimitsTerms } from './credit-limits'
import { VoucherDetail, VoucherForm } from './vouchers'
import { VoucherRegister } from './voucher-register'
import { ReportsCentre, ReportOutput, ReportStudio, ReportTemplates } from './reports-pages'
import { PaymentsCentre } from './transactions-pages'
import { PurchaseOrders } from './purchase-orders'
import { ReportsAnalytics } from './reports-analytics'
import { StockMovements } from './stock-movements'
import { CashBook } from './cashbook'
import { CashTransactions } from './cash-transactions'
import { ChequeVoucher } from './cheque-voucher'
import { ChequeActions } from './cheque-actions'
import { ChequePosting } from './cheque-posting'
import { ProductClasses } from './product-classes'
import { ProductReports } from './product-reports'
import { InventoryReports } from './inventory-reports'
import { SalesVoucher } from './sales-voucher'
import { BankAccounts } from './bank-accounts'
import { ProductCompanies } from './companies'
import { SalesReturn } from './sales-return'
import { ApprovalQueue, ChequeClearing, RecurringTemplates, SettingsPage } from './control-pages'
import { TodayWork } from './today-work'
import { InventoryWorkspace } from './inventory-pages'
import { ManualStockEntry } from './manual-stock'
import { SalesmanAttendance } from './attendance'
import { AttendanceEntry } from './attendance-entry'
import { PayrollPage } from './payroll'
import { PurchaseVoucher } from './purchase-voucher'
import { BankBook } from './bank-book'
import { StockVouchers } from './stock-vouchers'
import { PrintDocuments } from './print-documents'
import { PurchaseReturns } from './purchase-returns'
import { ProductCatalogue } from './product-catalogue'
import { MasterModal, ProductFormModal, EmployeeFormModal } from './master-form'
import { Button, Badge, PageHead, Kpi, Panel, SearchField, Modal, Table } from '@finsoft/ui'
import { money } from '@finsoft/ui'

export function Dashboard({go,data}:{go:(p:string)=>void;data:ReturnType<typeof usePersistentData>['data']}){
 const revenue=data.sales.reduce((a,s)=>a+s.amount,0), cogs=data.sales.reduce((a,s)=>a+s.qty*s.unitCost,0), stockValue=data.products.reduce((a,p)=>a+p.batches.reduce((x,b)=>x+b.stock*b.cost,0),0)
 const quickActions:[string,string,string,LucideIcon][]=[
  ['Create voucher','Post a journal or cash entry','/vouchers/new',ReceiptText],
  ['Sales invoice','Create a customer invoice','/sales?new=1',FilePlus2],
  ['Purchase invoice','Record a supplier bill','/purchasing?new=1',ShoppingBag],
  ['Record payment','Receive or pay funds','/payments',WalletCards],
  ['Purchase order','Raise a new stock order','/po',ClipboardPlus],
  ['Reports centre','Run financial reports','/reports',FileChartColumn],
 ]
 return <><div className="hero-band"><div><span className="hero-eyebrow">Sunday, 30 August 2026</span><h1>Good morning, Ahmed</h1><p>Here’s what is happening across Bhatti Traders today.</p></div><div className="hero-actions"><Button kind="secondary" onClick={()=>go('/reports')}><FileChartColumn/> View reports</Button><Button kind="primary" onClick={()=>go('/sales')}><Plus/> New sale</Button></div></div>
 <div className="kpi-grid"><Kpi label="Net sales today" value={money(revenue)} change={`${data.sales.length} posted invoices`} icon={CircleDollarSign}/><Kpi label="Gross profit" value={money(revenue-cogs)} change={`${revenue?Math.round((revenue-cogs)/revenue*100):0}% margin`} icon={TrendingUp} tone="teal"/><Kpi label="Receivables" value={money(data.sales.filter(s=>s.status==='Credit').reduce((a,s)=>a+s.amount,0))} change="From live credit sales" icon={WalletCards} tone="blue"/><Kpi label="Stock value" value={money(stockValue)} change={`${data.products.reduce((a,p)=>a+p.stock,0)} packs on hand`} icon={Boxes} tone="yellow"/></div>
 <section className="quick-actions" aria-labelledby="quick-actions-title"><div className="quick-actions-head"><div><h2 id="quick-actions-title">Quick actions</h2><p>Start your most-used workflows</p></div><span>6 shortcuts</span></div><div className="quick-actions-grid">{quickActions.map(([label,description,path,Icon],index)=><button type="button" onClick={()=>go(path)} key={label} className={`quick-action tone-${index+1}`}><span className="quick-action-icon"><Icon/></span><span className="quick-action-copy"><b>{label}</b><small>{description}</small></span><ChevronRight/></button>)}</div></section>
 <div className="dashboard-grid"><Panel title="Sales pulse" sub="Daily sales and purchase value · this week" action={<select className="compact"><option>This week</option><option>This month</option></select>}><div className="chart-lg"><ResponsiveContainer><AreaChart data={chartData}><defs><linearGradient id="sales" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1d9c52" stopOpacity=".3"/><stop offset="100%" stopColor="#1d9c52" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7ecf2"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`${v/1000}k`}/><Tooltip formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="sales" stroke="#1a8f4c" strokeWidth={3} fill="url(#sales)"/><Area type="monotone" dataKey="purchases" stroke="#2f7585" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="dot green"/>Sales Rs 1.18m</span><span><i className="dot teal"/>Purchases Rs 644k</span></div></Panel>
 <Panel title="Inventory health" sub="Value distributed by status"><div className="donut-row"><div className="donut"><ResponsiveContainer><PieChart><Pie data={[{v:72},{v:17},{v:11}]} dataKey="v" innerRadius={58} outerRadius={80} startAngle={90} endAngle={-270} paddingAngle={4}>{['#1d9c52','#f0be65','#dd6d72'].map(c=><Cell key={c} fill={c}/>)}</Pie></PieChart></ResponsiveContainer><div><b>1,248</b><small>SKUs</small></div></div><div className="health-list"><p><i className="dot green"/><span>Healthy stock</span><b>899</b></p><p><i className="dot yellow"/><span>Low stock</span><b>214</b></p><p><i className="dot red"/><span>Near expiry</span><b>135</b></p></div></div><Button kind="secondary" onClick={()=>go('/inventory')}>Review inventory <ArrowRight/></Button></Panel></div>
 <div className="lower-grid"><Panel title="Needs attention" sub="Priority tasks for your team"><div className="attention"><button onClick={()=>go('/procurement')}><span className="alert-icon amber"><AlertTriangle/></span><div><b>8 products below reorder level</b><small>Create a demand list before stock-out</small></div><ChevronRight/></button><button onClick={()=>go('/bank-book')}><span className="alert-icon blue"><Landmark/></span><div><b>5 cheques awaiting clearance</b><small>Total value Rs 214,000</small></div><ChevronRight/></button><button onClick={()=>go('/receivables')}><span className="alert-icon red"><ArrowDownRight/></span><div><b>12 batches expire within 90 days</b><small>Potential exposure Rs 86,400</small></div><ChevronRight/></button></div></Panel>
 <Panel title="Top products" sub="By sales value this month"><Table headers={['Product','Units','Revenue','Trend']} rows={[[<b>Panadol 500mg</b>,'864','Rs 311k',<Badge tone="good">↑ 12%</Badge>],[<b>Augmentin 625mg</b>,'218','Rs 227k',<Badge tone="good">↑ 8%</Badge>],[<b>Risek 20mg</b>,'310','Rs 189k',<Badge tone="warn">↓ 2%</Badge>]]}/></Panel></div></>
}

export function Products({products,onAddProduct,canCreate}:{products:ReturnType<typeof usePersistentData>['data']['products'];onAddProduct:(p:Product)=>void;canCreate:boolean}){
 const loc=useLocation(), navigate=useNavigate(); const [search,setSearch]=useState(new URLSearchParams(loc.search).get('q')||''),[category,setCategory]=useState('All'),[open,setOpen]=useState(false)
 const filtered=products.filter(p=>(category==='All'||p.category===category)&&`${p.name} ${p.generic} ${p.id}`.toLowerCase().includes(search.toLowerCase()))
 return <><PageHead eyebrow="Products / Product catalogue" title="Product catalogue" description="Manage medicines, pricing, batches and reorder controls." actions={<><Button kind="secondary"><Download/> Export</Button><Button disabled={!canCreate} onClick={()=>setOpen(true)}><Plus/> Add product</Button></>}/><div className="toolbar"><SearchField value={search} onChange={setSearch} placeholder="Search product, generic or code..."/><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{[...new Set(products.map(p=>p.category))].map(x=><option key={x}>{x}</option>)}</select><Button kind="secondary"><Filter/> More filters</Button><span className="record-count">{filtered.length} products</span></div>
 <Panel title="All products" sub="Live stock and pricing across every batch"><Table headers={['Product','Category','Batches / next expiry','Stock','Avg. cost','Retail price','Status','']} rows={filtered.map(p=>[<button className="product-cell" onClick={()=>navigate(`/products/${p.id}`)}><span><Pill/></span><div><b>{p.name}</b><small>{p.id} · {p.generic}</small></div></button>,p.category,<div><b>{p.batches.length} batches</b><small>{[...p.batches].sort((a,b)=>a.expiry.localeCompare(b.expiry))[0]?.expiry}</small></div>,<b>{p.stock}</b>,money(Math.round(p.batches.reduce((a,b)=>a+b.cost*b.stock,0)/Math.max(1,p.stock))),<b>{money(p.price)}</b>,p.stock<=p.reorder?<Badge tone="warn">Low stock</Badge>:<Badge tone="good">In stock</Badge>,<button aria-label={`View ${p.name}`} className="table-action" onClick={()=>navigate(`/products/${p.id}`)}><Eye/> View</button>])}/></Panel>
 {open&&<ProductFormModal open={open} list={products} onClose={()=>setOpen(false)} onSave={onAddProduct}/>}</>
}
export function Purchasing({products,purchases,onAdd,canCreate}:{products:ReturnType<typeof usePersistentData>['data']['products'];purchases:Purchase[];onAdd:(p:Purchase)=>void;canCreate:boolean}){
 const location=useLocation(),[open,setOpen]=useState(()=>new URLSearchParams(location.search).get('new')==='1'),[search,setSearch]=useState(''),navigate=useNavigate()
 const [form,setForm]=useState({supplier:'Getz Pharma',product:products[0].name,qty:10,status:'Posted'})
 const submit=(e:FormEvent)=>{e.preventDefault();const product=products.find(p=>p.name===form.product)!;onAdd({id:`PUR-2026-${String(185+purchases.length).padStart(4,'0')}`,date:'30 Aug 2026',supplier:form.supplier,product:form.product,qty:Number(form.qty),amount:Number(form.qty)*product.cost,status:form.status as Purchase['status'],batch:product.batch,expiry:product.expiry,unitCost:product.cost});setOpen(false)}
 const rows=purchases.filter(x=>Object.values(x).join(' ').toLowerCase().includes(search.toLowerCase()))
 return <><PageHead eyebrow="Trading & Inventory / Purchasing" title="Purchases" description="Receive supplier invoices and post stock in one controlled workflow." actions={<Button disabled={!canCreate} onClick={()=>setOpen(true)}><Plus/> New purchase</Button>}/><div className="kpi-grid mini"><Kpi label="Purchases this month" value="Rs 2.46m" change="8.2% vs July" icon={ShoppingBag}/><Kpi label="Open payables" value="Rs 784k" change="14 suppliers" icon={ReceiptText} tone="teal"/><Kpi label="Draft invoices" value="6" change="Rs 114k pending" icon={FileText} tone="yellow"/></div><div className="toolbar"><SearchField value={search} onChange={setSearch} placeholder="Search purchase or supplier..."/><Button kind="secondary"><Filter/> Filter</Button></div><Panel title="Purchase register" sub="Newest supplier invoices first"><Table headers={['Purchase no.','Date','Supplier','Product','Quantity','Amount','Status','']} rows={rows.map(p=>[<button className="linkable" onClick={()=>navigate(`/purchases/${p.id}`)}>{p.id}</button>,p.date,p.supplier,p.product,p.qty,<b>{money(p.amount)}</b>,<Badge tone={p.status==='Posted'?'good':'warn'}>{p.status}</Badge>,<button aria-label={`View ${p.id}`} className="table-action" onClick={()=>navigate(`/purchases/${p.id}`)}><Eye/> View</button>])}/></Panel>
 {open&&<Modal title="Create purchase invoice" onClose={()=>setOpen(false)} wide><form onSubmit={submit}><div className="steps"><span className="current"><i>1</i>Invoice details</span><span><i>2</i>Review</span><span><i>3</i>Post stock</span></div><div className="form-grid"><label>Supplier<select value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}><option>Getz Pharma</option><option>GlaxoSmithKline</option><option>Abbott Laboratories</option><option>The Searle Company</option></select></label><label>Invoice date<input type="date" defaultValue="2026-08-30"/></label><label className="span-2">Product<select value={form.product} onChange={e=>setForm({...form,product:e.target.value})}>{products.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Quantity<input min="1" type="number" value={form.qty} onChange={e=>setForm({...form,qty:Number(e.target.value)})}/></label><label>Posting status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Posted</option><option>Draft</option></select></label></div><div className="summary-strip"><span>Selected item<b>{form.product}</b></span><span>Stock impact<b>+{form.qty} packs</b></span><span>Estimated total<b>{money(form.qty*(products.find(p=>p.name===form.product)?.cost||0))}</b></span></div><div className="modal-foot"><Button kind="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit"><Check/> Save purchase</Button></div></form></Modal>}</>
}

export function Sales({products,sales,onAdd,canCreate}:{products:ReturnType<typeof usePersistentData>['data']['products'];sales:Sale[];onAdd:(p:Sale)=>void;canCreate:boolean}){
 const location=useLocation(),[open,setOpen]=useState(()=>new URLSearchParams(location.search).get('new')==='1'),[tab,setTab]=useState('All sales'),navigate=useNavigate(),[form,setForm]=useState({mode:'Retail',customer:'Walk-in Customer',product:products[0].name,qty:1,status:'Paid'})
 const submit=(e:FormEvent)=>{e.preventDefault();const product=products.find(p=>p.name===form.product)!;if(form.qty>product.stock)return;const fefo=[...product.batches].filter(b=>b.stock>0).sort((a,b)=>a.expiry.localeCompare(b.expiry))[0];onAdd({id:`INV-${26815+sales.length}`,date:'30 Aug 2026',customer:form.customer,product:form.product,qty:Number(form.qty),amount:Number(form.qty)*product.price,mode:form.mode,status:form.status as Sale['status'],batch:fefo?.id??product.batch,unitCost:fefo?.cost??product.cost});setOpen(false)}
 const visible=sales.filter(s=>tab==='All sales'||s.status===tab)
 return <><PageHead eyebrow="Trading & Inventory / Sales & POS" title="Sales & point of sale" description="Process retail, wholesale, hospital and clinic sales with FEFO allocation." actions={<><Button kind="secondary" onClick={()=>navigate('/sales/voucher')}><FileText/> Sales voucher</Button><Button disabled={!canCreate} onClick={()=>setOpen(true)}><Plus/> New sale</Button></>}/><div className="kpi-grid mini"><Kpi label="Sales today" value="Rs 192,480" change="84 invoices" icon={CircleDollarSign}/><Kpi label="Cash received" value="Rs 128,200" change="66.6% of sales" icon={WalletCards} tone="teal"/><Kpi label="Credit sales" value="Rs 64,280" change="18 invoices" icon={ReceiptText} tone="yellow"/></div><div className="tabs">{['All sales','Paid','Credit'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><Panel title="Sales register" sub={`${visible.length} matching invoices`}><Table headers={['Invoice','Date','Customer','Mode','Product','Quantity','Total','Status','']} rows={visible.map(s=>[<button className="linkable" onClick={()=>navigate(`/sales/${s.id}`)}>{s.id}</button>,s.date,s.customer,<Badge tone="info">{s.mode}</Badge>,s.product,s.qty,<b>{money(s.amount)}</b>,<Badge tone={s.status==='Paid'?'good':'warn'}>{s.status}</Badge>,<button aria-label={`View ${s.id}`} className="table-action" onClick={()=>navigate(`/sales/${s.id}`)}><Eye/> View</button>])}/></Panel>
 {open&&<Modal title="New sales invoice" onClose={()=>setOpen(false)} wide><form onSubmit={submit}><div className="mode-picker">{['Retail','Wholesale'].map(m=><button type="button" className={form.mode===m?'active':''} onClick={()=>setForm({...form,mode:m,customer:m==='Retail'?'Walk-in Customer':form.customer})} key={m}>{m}</button>)}</div><div className="form-grid"><label>Customer<input value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></label><label>Payment<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Paid</option><option>Credit</option></select></label><label className="span-2">Product / FEFO batch<select value={form.product} onChange={e=>setForm({...form,product:e.target.value})}>{products.filter(p=>p.stock>0).map(p=><option key={p.id}>{p.name} — {p.batch} — {p.stock} available</option>)}</select><small className="field-note"><Sparkles/> Earliest valid expiry is automatically selected</small></label><label>Quantity<input type="number" min="1" max={products.find(p=>p.name===form.product)?.stock} value={form.qty} onChange={e=>setForm({...form,qty:Number(e.target.value)})}/></label><label>Unit price<input readOnly value={money(products.find(p=>p.name===form.product)?.price||0)}/></label></div><div className="invoice-total"><span>Invoice total</span><b>{money(form.qty*(products.find(p=>p.name===form.product)?.price||0))}</b></div><div className="modal-foot"><Button kind="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit"><Check/> Post sale</Button></div></form></Modal>}</>
}

export function Masters({masters,onAddMaster,canCreate}:{masters:Master[];onAddMaster:(m:Master)=>void;canCreate:boolean}){
 const loc=useLocation();const [tab,setTab]=useState('Accounts & parties'),[query,setQuery]=useState(''),navigate=useNavigate(),[open,setOpen]=useState(new URLSearchParams(loc.search).get('new'))
 const typeOf=(t:string)=>t==='Banks'?'Bank':t==='Departments'?'Department':t==='Doctors'?'Doctor':t==='Locations'?'Account':'Account'
 const rows=masters.filter(m=>`${m.code} ${m.name} ${m.type} ${m.balanceType}`.toLowerCase().includes(query.toLowerCase())).filter(m=>tab==='Accounts & parties'||(tab==='Banks'&&m.type==='Bank')||(tab==='Departments'&&m.type==='Department')||(tab==='Doctors'&&m.type==='Doctor'))
 return <><PageHead eyebrow="Masters / Business masters" title="Business masters" description="One reliable directory for accounts, parties, locations and classifications." actions={<Button disabled={!canCreate} onClick={()=>setOpen('all')}><Plus/> Add master record</Button>}/><div className="tabs">{['Accounts & parties','Locations','Banks','Departments','Doctors'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="toolbar"><SearchField value={query} onChange={setQuery}/><Button kind="secondary"><Download/> Export</Button></div><Panel title={tab} sub={`${rows.length} active records`}><Table headers={['Code','Name','Record type','Balance type','Status','']} rows={rows.map(m=>[<b>{m.code}</b>,<button className="linkable" onClick={()=>navigate(`/masters/${m.code}`)}>{m.name}</button>,m.type,m.balanceType,<Badge tone={m.status==='Active'?'good':'warn'}>{m.status}</Badge>,<button aria-label={`Details ${m.name}`} className="table-action" onClick={()=>navigate(`/masters/${m.code}`)}><Eye/> Details</button>])}/></Panel>
 {open&&<MasterModal open={!!open} list={masters} presetType={{customer:'Customer',vendor:'Supplier',account:'Account',account2:'Account'}[open]??(open==='all'?typeOf(tab):'Account')} onClose={()=>{setOpen(null);navigate('/masters',{replace:true})}} onSave={onAddMaster}/>}</>
}
export function Procurement(){const [checked,setChecked]=useState<string[]>([]);const items=[['Augmentin 625mg',42,60,80,'Getz Pharma'],['Calpol Suspension',18,30,48,'Sami Pharmaceuticals'],['Humulin 70/30',12,20,30,'The Searle Company'],['Ventolin Inhaler',31,35,52,'GlaxoSmithKline']];return <><PageHead eyebrow="Trading & Inventory / Demand & PO" title="Smart procurement" description="Turn reorder signals into supplier-ready purchase orders." actions={<Button><Plus/> Create purchase order</Button>}/><div className="procurement-callout"><span><Sparkles/></span><div><b>Finsoft found 4 replenishment opportunities</b><p>Suggested quantities consider reorder levels, current stock and recent sales velocity.</p></div><Button kind="secondary">Review logic</Button></div><Panel title="Reorder suggestions" sub={`${checked.length} selected · suggested order value Rs 128,640`} action={<Button kind="secondary"><ClipboardCheck/> Convert selected</Button>}><Table headers={['','Product','Current','Reorder at','Suggested qty','Preferred supplier','Priority']} rows={items.map(r=>[<input type="checkbox" checked={checked.includes(String(r[0]))} onChange={()=>setChecked(x=>x.includes(String(r[0]))?x.filter(v=>v!==r[0]):[...x,String(r[0])])}/>,<b>{r[0]}</b>,r[1],r[2],r[3],r[4],<Badge tone={Number(r[1])<20?'danger':'warn'}>{Number(r[1])<20?'Critical':'Medium'}</Badge>])}/></Panel><div className="lower-grid"><Panel title="Purchase order pipeline" sub="August 2026"><div className="pipeline"><div><b>8</b><span>Draft</span></div><ArrowRight/><div><b>5</b><span>Sent</span></div><ArrowRight/><div><b>3</b><span>Part received</span></div><ArrowRight/><div><b>21</b><span>Received</span></div></div></Panel><Panel title="Supplier performance" sub="On-time delivery rate"><div className="supplier-bars"><p><span>Getz Pharma</span><b>96%</b></p><i><em style={{width:'96%'}}/></i></div><div className="supplier-bars"><p><span>GSK Pakistan</span><b>91%</b></p><i><em style={{width:'91%'}}/></i></div><div className="supplier-bars"><p><span>Abbott Labs</span><b>86%</b></p><i><em style={{width:'86%'}}/></i></div></Panel></div></>}

export function HR({employees,onAddEmployee,canCreate}:{employees:string[][];onAddEmployee:(e:string[])=>void;canCreate:boolean}){
 const [tab,setTab]=useState('Employees'),navigate=useNavigate(),[open,setOpen]=useState(false)
 return <><PageHead eyebrow="HR & Payroll / Employees" title="HR & payroll" description="Bring attendance, compensation and sales performance into one workspace." actions={<><Button kind="secondary"><CalendarDays/> Mark attendance</Button><Button disabled={!canCreate} onClick={()=>setOpen(true)}><Plus/> Add employee</Button></>}/><div className="kpi-grid"><Kpi label="Total employees" value={String(employees.length)} change="On the register" icon={Users}/><Kpi label="Payroll · August" value="Rs 6.24m" change="Processing on 31 Aug" icon={WalletCards} tone="teal"/><Kpi label="Field sales team" value="18" change="84% target achieved" icon={TrendingUp} tone="blue"/><Kpi label="On leave" value={String(employees.filter(r=>r[5]==='Leave').length)} change="2 approvals pending" icon={CalendarDays} tone="yellow"/></div><div className="tabs">{['Employees','Attendance','Payroll','Sales targets','Allowances','Final settlement'].map(t=><button onClick={()=>t==='Payroll'?navigate('/hr/payroll'):setTab(t)} className={tab===t?'active':''} key={t}>{t}</button>)}</div><Panel title={tab} sub="August 2026 cycle"><Table headers={['Employee ID','Employee','Designation','Branch','Gross salary','Today']} rows={employees.map(r=>[<button className="linkable" onClick={()=>navigate(`/hr/employees/${r[0]}`)}>{r[0]}</button>,<button className="linkable" onClick={()=>navigate(`/hr/employees/${r[0]}`)}>{r[1]}</button>,r[2],r[3],<b>{r[4]}</b>,<Badge tone={r[5]==='Present'?'good':r[5]==='Field'?'info':'warn'}>{r[5]}</Badge>])}/></Panel>
 {open&&<EmployeeFormModal open={open} list={employees} onClose={()=>setOpen(false)} onSave={onAddEmployee}/>}</>
}
export function Admin({role,setRole,initialTab='Users'}:{role:string;setRole:(r:string)=>void;initialTab?:string}){const [tab,setTab]=useState(initialTab),navigate=useNavigate();return <><PageHead eyebrow="System / Administration" title="Admin & control" description="Manage people, permissions, periods and every security-sensitive action." actions={<Button><Plus/> Invite user</Button>}/><div className="admin-banner"><span><ShieldCheck/></span><div><b>Security posture is strong</b><p>2FA is enabled for 14 of 16 users. No unusual activity detected.</p></div><Badge tone="good">92 / 100</Badge></div><div className="tabs">{['Users','Roles & permissions','Fiscal periods','Security','Active sessions','Audit log'].map(t=><button onClick={()=>setTab(t)} className={tab===t?'active':''} key={t}>{t}</button>)}</div>{tab==='Roles & permissions'?<Panel title="Role access preview" sub="Switch role to preview the application exactly as that user"><div className="role-cards">{Object.entries(roles).map(([name,permissions])=><button className={role===name?'selected':''} onClick={()=>setRole(name)} key={name}><span>{name.slice(0,2).toUpperCase()}</span><div><b>{name}</b><small>{permissions.includes('all')?'Full system access':`${permissions.length} modules enabled`}</small></div>{role===name&&<Check/>}</button>)}</div></Panel>:tab==='Active sessions'?<Panel title="Active sessions" sub="All signed-in devices across branches"><Table headers={['User','Role','Device','Location','Last active','Status']} rows={users.flatMap(u=>u.sessions.map(s=>[<button className="linkable" onClick={()=>navigate(`/admin/users/${u.id}`)}>{u.name}</button>,u.role,s.device,s.location,s.lastActive,<Badge tone={u.status==='Active'?'good':'warn'}>{u.status}</Badge>]))}/></Panel>:tab==='Audit log'?<Panel title="Audit log" sub="Security-sensitive actions across the organisation"><Table headers={['Date','User','Action','Detail']} rows={users.flatMap(u=>u.audit.map(a=>[a.date,<button className="linkable" onClick={()=>navigate(`/admin/users/${u.id}`)}>{u.name}</button>,a.action,a.detail]))}/></Panel>:<Panel title={tab} sub="Administration records"><Table headers={['User','Role','Branch','2FA','Status']} rows={users.map(u=>[<button className="linkable" onClick={()=>navigate(`/admin/users/${u.id}`)}>{u.name}</button>,u.role,u.branch,u.twoFactor?<Badge tone="good">Enabled</Badge>:<Badge tone="warn">Off</Badge>,<Badge tone={u.status==='Active'?'good':'warn'}>{u.status}</Badge>])}/></Panel>}</>}

