'use client'
import { useMemo, useState, type FormEvent } from 'react'
import { useNavigate } from '@/lib/router'
import { AlertTriangle, ArrowDownRight, ArrowLeftRight, ArrowRight, Boxes, CalendarDays, Check, ClipboardCheck, ClipboardList, Clock3, Download, History, PackageCheck, Plus, ShieldCheck, Warehouse } from 'lucide-react'
import type { Product, StockMovement } from '@/mocks/api'
import type { AppData } from '@/mocks/api'
import { money } from '@finsoft/ui'
import { Badge, Button, Kpi, PageHead, Panel, SearchField, Table } from '@finsoft/ui'
import { StockTransferPage } from './stock-transfer'

type View='overview'|'stock-in'|'issue'|'transfer'|'count'|'as-of'|'batches'
type Props={data:AppData;view:View;onPost:(movement:StockMovement)=>void}

const inventoryLinks=[
 {view:'overview',label:'Current stock',sub:'Live availability',path:'/inventory',icon:Boxes},
 {view:'stock-in',label:'Stock in',sub:'Receive inventory',path:'/inventory/stock-in',icon:PackageCheck},
 {view:'issue',label:'Issue / adjust',sub:'Reduce or correct',path:'/inventory/issue',icon:ArrowDownRight},
 {view:'transfer',label:'Stock transfer',sub:'Move between stores',path:'/inventory/transfer',icon:ArrowLeftRight},
 {view:'count',label:'Physical count',sub:'Reconcile stock',path:'/inventory/count',icon:ClipboardCheck},
 {view:'batches',label:'Batch & expiry',sub:'Control shelf life',path:'/inventory/batches',icon:Clock3},
] as const
const branches=['Lahore Main','Rawalpindi','Karachi Warehouse']
const appToday='2026-08-30'
const displayDate=(iso:string)=>new Date(`${iso}T12:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})
const makeId=(prefix:string)=>`${prefix}-${Date.now()}`

function InventoryNav({view}:{view:View}){
 const navigate=useNavigate()
 return <div className="inventory-nav" aria-label="Inventory operations">{inventoryLinks.map(item=>{const Icon=item.icon;return <button key={item.view} type="button" className={view===item.view?'active':''} onClick={()=>navigate(item.path)}><span><Icon/></span><div><b>{item.label}</b><small>{item.sub}</small></div>{view===item.view&&<i/>}</button>})}</div>
}

function ProductBatchFields({products,productId,setProductId,batch,setBatch}:{products:Product[];productId:string;setProductId:(value:string)=>void;batch:string;setBatch:(value:string)=>void}){
 const product=products.find(p=>p.id===productId)??products[0]
 const choose=(id:string)=>{setProductId(id);setBatch(products.find(p=>p.id===id)?.batches[0]?.id??'')}
 return <><label>Product<select aria-label="Product" value={productId} onChange={e=>choose(e.target.value)}>{products.map(p=><option value={p.id} key={p.id}>{p.id} · {p.name}</option>)}</select></label><label>Batch<select aria-label="Batch" value={batch} onChange={e=>setBatch(e.target.value)}>{product?.batches.map(b=><option key={b.id} value={b.id}>{b.id} · {b.stock} available</option>)}</select></label></>
}

function OperationSuccess({reference,onAgain}:{reference:string;onAgain:()=>void}){
 return <div className="inventory-success"><span><Check/></span><div><b>Stock operation posted</b><p>{reference} is now reflected in live inventory and the movement ledger.</p></div><Button kind="secondary" onClick={onAgain}>Post another</Button></div>
}

function StockIn({data,onPost}:{data:AppData;onPost:Props['onPost']}){
 const first=data.products[0];const [productId,setProductId]=useState(first.id),[batch,setBatch]=useState(''),[expiry,setExpiry]=useState(first.expiry),[qty,setQty]=useState(10),[cost,setCost]=useState(first.cost),[branch,setBranch]=useState(branches[0]),[reference,setReference]=useState(''),[posted,setPosted]=useState('')
 const product=data.products.find(p=>p.id===productId)??first
 const pickProduct=(id:string)=>{const p=data.products.find(x=>x.id===id)??first;setProductId(id);setCost(p.cost);setExpiry(p.expiry)}
 const submit=(e:FormEvent)=>{e.preventDefault();if(!batch.trim()||qty<1)return;const ref=reference.trim()||makeId('SIN');onPost({id:makeId('MOV'),date:displayDate(appToday),product:product.name,batch:batch.trim(),type:'Stock In',qty:Number(qty),reference:ref,to:branch,note:'Manual stock receipt',expiry,unitCost:cost});setPosted(ref)}
 if(posted)return <OperationSuccess reference={posted} onAgain={()=>{setPosted('');setReference('');setBatch('');setQty(10)}}/>
 return <div className="inventory-work-grid"><Panel title="Receive stock" sub="Enter the batch exactly as printed on the supplier pack"><form className="stock-form" onSubmit={submit}><div className="form-grid"><label className="span-2">Product<select value={productId} onChange={e=>pickProduct(e.target.value)}>{data.products.map(p=><option value={p.id} key={p.id}>{p.id} · {p.name}</option>)}</select></label><label>Receiving location<select value={branch} onChange={e=>setBranch(e.target.value)}>{branches.map(x=><option key={x}>{x}</option>)}</select></label><label>Receipt date<input type="date" value={appToday} readOnly/></label><label>Batch number<input required placeholder="e.g. AU-611C" value={batch} onChange={e=>setBatch(e.target.value)}/></label><label>Expiry date<input required type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label>Quantity<input required type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Unit cost<input required type="number" min="0" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label className="span-2">Supplier reference<input placeholder="Optional — generated automatically" value={reference} onChange={e=>setReference(e.target.value)}/></label></div><div className="stock-post-bar"><div><small>Stock value to add</small><b>{money(qty*cost)}</b></div><Button type="submit"><PackageCheck/> Post stock in</Button></div></form></Panel><Panel title="Receipt checks" sub="Complete before posting"><div className="inventory-checklist"><p><span><ShieldCheck/></span><b>Batch traceability</b><small>Batch and expiry are mandatory</small></p><p><span><Warehouse/></span><b>Destination</b><small>{branch}</small></p><p><span><Boxes/></span><b>New on-hand</b><small>{product.stock+qty} packs after receipt</small></p></div></Panel></div>
}

function IssueAdjustment({data,onPost}:{data:AppData;onPost:Props['onPost']}){
 const [mode,setMode]=useState<'Issue'|'Adjustment'>('Issue'),[productId,setProductId]=useState(data.products[0].id),[batch,setBatch]=useState(data.products[0].batches[0].id),[qty,setQty]=useState(1),[direction,setDirection]=useState<'Increase'|'Decrease'>('Decrease'),[reason,setReason]=useState('Internal consumption'),[department,setDepartment]=useState('Operations'),[posted,setPosted]=useState('')
 const product=data.products.find(p=>p.id===productId)??data.products[0],batchRow=product.batches.find(b=>b.id===batch)??product.batches[0]
 const signed=mode==='Issue'?-Math.abs(qty):direction==='Increase'?Math.abs(qty):-Math.abs(qty)
 const submit=(e:FormEvent)=>{e.preventDefault();if(!batchRow||signed<0&&Math.abs(signed)>batchRow.stock)return;const ref=makeId(mode==='Issue'?'ISS':'ADJ');onPost({id:makeId('MOV'),date:displayDate(appToday),product:product.name,batch:batchRow.id,type:mode,qty:signed,reference:ref,from:'Lahore Main',to:mode==='Issue'?department:undefined,note:reason});setPosted(ref)}
 if(posted)return <OperationSuccess reference={posted} onAgain={()=>setPosted('')}/>
 return <div className="inventory-work-grid"><Panel title="Stock issue & adjustment" sub="Every correction is recorded in the movement ledger"><form className="stock-form" onSubmit={submit}><div className="operation-toggle"><button type="button" onClick={()=>setMode('Issue')} className={mode==='Issue'?'active':''}>Stock issue</button><button type="button" onClick={()=>setMode('Adjustment')} className={mode==='Adjustment'?'active':''}>Inventory adjustment</button></div><div className="form-grid"><ProductBatchFields products={data.products} productId={productId} setProductId={setProductId} batch={batch} setBatch={setBatch}/>{mode==='Adjustment'&&<label>Direction<select value={direction} onChange={e=>setDirection(e.target.value as 'Increase'|'Decrease')}><option>Increase</option><option>Decrease</option></select></label>}<label>Quantity<input type="number" min="1" max={signed<0?batchRow?.stock:undefined} value={qty} onChange={e=>setQty(Number(e.target.value))}/></label>{mode==='Issue'&&<label>Issue to<select value={department} onChange={e=>setDepartment(e.target.value)}><option>Operations</option><option>Sales counter</option><option>Samples</option><option>Damaged goods</option></select></label>}<label className="span-2">Reason / notes<textarea required rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label></div>{signed<0&&qty>(batchRow?.stock??0)&&<div className="stock-warning"><AlertTriangle/> Quantity exceeds the selected batch balance.</div>}<div className="stock-post-bar"><div><small>Balance after posting</small><b>{Math.max(0,(batchRow?.stock??0)+signed)} packs</b></div><Button type="submit" disabled={signed<0&&qty>(batchRow?.stock??0)}><Check/> Post {mode.toLowerCase()}</Button></div></form></Panel><Panel title="Selected batch" sub="Live availability"><div className="batch-focus"><span><Boxes/></span><h3>{product.name}</h3><p>{batchRow?.id} · Expires {batchRow?.expiry}</p><b>{batchRow?.stock??0}</b><small>packs available</small></div></Panel></div>
}

function PhysicalCount({data,onPost}:{data:AppData;onPost:Props['onPost']}){
 const rows=useMemo(()=>data.products.flatMap(p=>p.batches.map(b=>({product:p,batch:b}))),[data.products]);const [query,setQuery]=useState(''),[counts,setCounts]=useState<Record<string,number>>(()=>Object.fromEntries(rows.map(r=>[`${r.product.id}|${r.batch.id}`,r.batch.stock]))),[posted,setPosted]=useState('')
 const visible=rows.filter(r=>`${r.product.name} ${r.batch.id}`.toLowerCase().includes(query.toLowerCase())),variance=rows.reduce((sum,r)=>sum+(counts[`${r.product.id}|${r.batch.id}`]??r.batch.stock)-r.batch.stock,0)
 const post=()=>{const ref=makeId('CNT');rows.forEach(r=>{const difference=(counts[`${r.product.id}|${r.batch.id}`]??r.batch.stock)-r.batch.stock;if(difference)onPost({id:`${makeId('MOV')}-${r.batch.id}`,date:displayDate(appToday),product:r.product.name,batch:r.batch.id,type:'Count',qty:difference,reference:ref,from:'Lahore Main',note:'Physical count variance'});});setPosted(ref)}
 if(posted)return <OperationSuccess reference={posted} onAgain={()=>setPosted('')}/>
 return <><div className="count-toolbar"><div><span><ClipboardList/></span><div><b>Count sheet · Lahore Main</b><small>{rows.length} batch lines · 30 Aug 2026</small></div></div><SearchField value={query} onChange={setQuery} placeholder="Search product or batch..."/><div className={variance?'count-variance alert':'count-variance'}><small>Net variance</small><b>{variance>0?'+':''}{variance}</b></div><Button onClick={post} disabled={!variance}><ClipboardCheck/> Post count</Button></div><Panel title="Physical inventory count" sub="Enter the quantity physically found for each batch"><Table headers={['Product','Batch','Expiry','System qty','Physical qty','Variance','Status']} rows={visible.map(r=>{const key=`${r.product.id}|${r.batch.id}`,physical=counts[key]??r.batch.stock,diff=physical-r.batch.stock;return [<div><b>{r.product.name}</b><small>{r.product.id}</small></div>,r.batch.id,r.batch.expiry,r.batch.stock,<input className="count-input" aria-label={`Physical count ${r.product.name} ${r.batch.id}`} type="number" min="0" value={physical} onChange={e=>setCounts(c=>({...c,[key]:Number(e.target.value)}))}/>,<b className={diff?'variance-value':''}>{diff>0?'+':''}{diff}</b>,diff?<Badge tone="warn">Review</Badge>:<Badge tone="good">Matched</Badge>]})}/></Panel></>
}

function CurrentStock({data}:{data:AppData}){
 const navigate=useNavigate(),[query,setQuery]=useState(''),[branch,setBranch]=useState('All locations'),filtered=data.products.filter(p=>`${p.id} ${p.name} ${p.generic}`.toLowerCase().includes(query.toLowerCase()))
 const total=data.products.reduce((a,p)=>a+p.batches.reduce((x,b)=>x+b.stock*b.cost,0),0),units=data.products.reduce((a,p)=>a+p.stock,0),near=data.products.flatMap(p=>p.batches).filter(b=>b.expiry<='2027-02-28').length
 return <><div className="kpi-grid"><Kpi label="Inventory value" value={money(total)} change="Across all active batches" icon={Boxes}/><Kpi label="Units on hand" value={String(units)} change={`${data.products.length} active SKUs`} icon={PackageCheck} tone="teal"/><Kpi label="Below reorder" value={String(data.products.filter(p=>p.stock<=p.reorder).length)} change="Requires replenishment" icon={AlertTriangle} tone="yellow"/><Kpi label="Expiry watch" value={String(near)} change="Batches within 6 months" icon={Clock3} tone="red"/></div><div className="toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search SKU, product or generic..."/><select value={branch} onChange={e=>setBranch(e.target.value)}><option>All locations</option>{branches.map(x=><option key={x}>{x}</option>)}</select><Button kind="secondary" onClick={()=>navigate('/inventory/as-of')}><CalendarDays/> Stock as on date</Button><Button kind="secondary" onClick={()=>navigate('/inventory/movements/history')}><History/> Movement ledger</Button></div><Panel title="Current stock by product" sub={`${filtered.length} products · ${branch}`}><Table headers={['Product','Category','Batches','Next expiry','On hand','Reorder at','Value','Health','']} rows={filtered.map(p=>{const next=[...p.batches].filter(b=>b.stock>0).sort((a,b)=>a.expiry.localeCompare(b.expiry))[0];return [<div><b>{p.name}</b><small>{p.id} · {p.generic}</small></div>,p.category,p.batches.length,next?.expiry??'—',<b>{p.stock}</b>,p.reorder,money(p.batches.reduce((a,b)=>a+b.stock*b.cost,0)),p.stock<=p.reorder?<Badge tone="warn">Reorder</Badge>:<Badge tone="good">Healthy</Badge>,<button className="table-action" onClick={()=>navigate(`/products/${p.id}`)}>View <ArrowRight/></button>]})}/></Panel></>
}

function BatchExpiry({data}:{data:AppData}){
 const [window,setWindow]=useState('All'),[query,setQuery]=useState('');const today=new Date(`${appToday}T00:00:00`).getTime();const rows=data.products.flatMap(p=>p.batches.map(b=>{const days=Math.ceil((new Date(`${b.expiry}T00:00:00`).getTime()-today)/86400000);return {product:p,batch:b,days}})).filter(r=>`${r.product.name} ${r.batch.id}`.toLowerCase().includes(query.toLowerCase())).filter(r=>window==='All'||window==='Expired'&&r.days<0||window==='90 days'&&r.days>=0&&r.days<=90||window==='6 months'&&r.days>90&&r.days<=183)
 return <><div className="expiry-summary"><button onClick={()=>setWindow('Expired')} className={window==='Expired'?'active danger':''}><span>Expired</span><b>{data.products.flatMap(p=>p.batches).filter(b=>b.expiry<appToday).length}</b><small>Quarantine immediately</small></button><button onClick={()=>setWindow('90 days')} className={window==='90 days'?'active warn':''}><span>Next 90 days</span><b>{data.products.flatMap(p=>p.batches).filter(b=>b.expiry>=appToday&&b.expiry<='2026-11-28').length}</b><small>Priority sale / return</small></button><button onClick={()=>setWindow('6 months')} className={window==='6 months'?'active':''}><span>Within 6 months</span><b>{data.products.flatMap(p=>p.batches).filter(b=>b.expiry>'2026-11-28'&&b.expiry<='2027-02-28').length}</b><small>Monitor closely</small></button><button onClick={()=>setWindow('All')} className={window==='All'?'active good':''}><span>All batches</span><b>{data.products.flatMap(p=>p.batches).length}</b><small>Complete register</small></button></div><div className="toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search product or batch..."/><span className="record-count">{rows.length} batch records</span><Button kind="secondary"><Download/> Export register</Button></div><Panel title="Batch & expiry register" sub={`${window} · FEFO priority order`}><Table headers={['Product','Batch','Expiry','Days remaining','Qty','Value','Disposition']} rows={[...rows].sort((a,b)=>a.days-b.days).map(r=>[<div><b>{r.product.name}</b><small>{r.product.id}</small></div>,r.batch.id,r.batch.expiry,<b>{r.days<0?`${Math.abs(r.days)} days overdue`:`${r.days} days`}</b>,r.batch.stock,money(r.batch.stock*r.batch.cost),r.days<0?<Badge tone="danger">Quarantine</Badge>:r.days<=90?<Badge tone="warn">Priority</Badge>:<Badge tone="good">Saleable</Badge>])}/></Panel></>
}

function StockAsOf({data}:{data:AppData}){
 const [date,setDate]=useState(appToday),[query,setQuery]=useState('');const cutoff=new Date(`${date}T23:59:59`).getTime();const after=(m:StockMovement)=>{const parsed=Date.parse(m.date);return Number.isFinite(parsed)&&parsed>cutoff};const rows=data.products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=>{const later=data.movements.filter(m=>m.product===p.name&&m.type!=='Transfer'&&after(m)).reduce((a,m)=>a+m.qty,0);return {...p,asOf:Math.max(0,p.stock-later)}})
 return <><div className="asof-banner"><span><CalendarDays/></span><div><b>Historical stock position</b><p>Balances are reconstructed from the movement ledger at close of business.</p></div><label>As on date<input type="date" max={appToday} value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search product..."/><select><option>All locations</option>{branches.map(x=><option key={x}>{x}</option>)}</select><Button kind="secondary"><Download/> Export snapshot</Button></div><Panel title={`Stock as on ${displayDate(date)}`} sub="Quantity and weighted value at the selected cutoff"><Table headers={['Product','Category','Quantity','Avg. cost','Stock value','Reorder status']} rows={rows.map(p=>[<b>{p.name}</b>,p.category,p.asOf,money(p.cost),<b>{money(p.asOf*p.cost)}</b>,p.asOf<=p.reorder?<Badge tone="warn">Below level</Badge>:<Badge tone="good">Sufficient</Badge>])}/></Panel></>
}

export function InventoryWorkspace({data,view,onPost}:Props){
 const navigate=useNavigate()
 const titles:Record<View,[string,string]>={overview:['Inventory control','Live stock, valuation and operational control across every location.'],'stock-in':['Stock in','Receive non-purchase stock with full batch and expiry traceability.'],issue:['Stock issue & adjustment','Issue internal stock or correct a verified inventory variance.'],transfer:['Stock transfer','Move traceable batches between branches and warehouses.'],count:['Physical count','Count batch-level inventory and post only reviewed variances.'],'as-of':['Stock as on date','Reconstruct inventory quantities and value at a prior cutoff.'],batches:['Batch & expiry control','Manage FEFO priority, expiring stock and quarantine decisions.']}
 const [title,description]=titles[view]
 if(view==='transfer')return <><InventoryNav view={view}/><StockTransferPage data={data} onPost={onPost}/></>
 return <><PageHead eyebrow="Inventory / Stock operations" title={title} description={description} actions={view==='overview'?<Button onClick={()=>navigate('/inventory/stock-in')}><Plus/> New operation</Button>:undefined}/><InventoryNav view={view}/>{view==='overview'?<CurrentStock data={data}/>:view==='stock-in'?<StockIn data={data} onPost={onPost}/>:view==='issue'?<IssueAdjustment data={data} onPost={onPost}/>:view==='count'?<PhysicalCount data={data} onPost={onPost}/>:view==='as-of'?<StockAsOf data={data}/>:<BatchExpiry data={data}/>}</>
}
